name: Deploy Judy's Dinner to EC2

on:
  push:
    branches:
      - master  # 或 main，依你 repo 而定

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ec2-user/projects/python/line-bot-judys-dinner
          git reset --hard HEAD
          git pull origin master
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart judys-dinner
